"""Generated tests for my-mcp-server MCP server tools.

This file is automatically generated to test that all tools can be loaded
and executed successfully.
"""

import sys
from pathlib import Path

import pytest

# Add src to Python path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from core.server import DynamicMCPServer  # noqa: E402


class TestToolLoading:
    """Test that all tools can be loaded successfully."""

    def test_server_initialization(self) -> None:
        """Test that the server can be initialized."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        assert server is not None
        assert server.name == "Test Server"

    def test_tool_discovery(self) -> None:
        """Test that tools can be discovered."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")

        # Load tools without failing
        try:
            server.load_tools()
            assert True  # If we get here, loading succeeded
        except SystemExit:
            pytest.fail("Tool loading failed - server exited")

    def test_loaded_tools_count(self) -> None:
        """Test that expected tools are loaded."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()

        # We should have evidence, system, and reports tools
        assert len(server.loaded_tools) >= 3
        assert "evidence" in server.loaded_tools
        assert "system" in server.loaded_tools
        assert "reports" in server.loaded_tools

    def test_tool_functions_callable(self) -> None:
        """Test that loaded tool functions are callable."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()

        tools = server.get_tools_sync()
        for tool_name, tool in tools.items():
            assert hasattr(tool, 'fn'), f"Tool {tool_name} has no fn attribute"
            assert callable(tool.fn), f"Tool {tool_name} is not callable"


class TestEvidenceTools:
    """Test the evidence management tools."""

    def test_evidence_tools_exist(self) -> None:
        """Test that the evidence tools exist and can be loaded."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()

        assert "evidence" in server.loaded_tools
        
        tools = server.get_tools_sync()
        assert "evidence_search" in tools
        assert "evidence_chain_history" in tools
        assert "evidence_custody_transfer" in tools
        assert "evidence_integrity_check" in tools

class TestSystemTools:
    """Test the system management tools."""

    def test_system_tools_exist(self) -> None:
        """Test that the system tools exist and can be loaded."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()

        assert "system" in server.loaded_tools
        
        tools = server.get_tools_sync()
        assert "system_list_facilities" in tools
        assert "system_list_locations" in tools
        assert "system_alerts_monitor" in tools
        assert "system_personnel_list" in tools

class TestReportingTools:
    """Test the business intelligence and reporting tools."""

    def test_reporting_tools_exist(self) -> None:
        """Test that the reporting tools exist and can be loaded."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()

        assert "reports" in server.loaded_tools
        
        tools = server.get_tools_sync()
        assert "get_case_health_summary" in tools
        assert "find_compromised_evidence" in tools
        assert "get_officer_workload_analysis" in tools
