"""Tools package for knowledge-assistant MCP server.

This file is automatically generated by the dynamic loading system.
Do not edit manually - it will be overwritten when tools are loaded.
"""

from .echo import echo
from .weather import weather

__all__ = ["echo", "weather"]
